# Generated by Django 4.2.7 on 2023-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_amplificadores_user_alter_monitores_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplificadores',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
